language: php

git:
    depth: 1

cache:
    directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

php:
- 7.1
- 7.2
- 7.3

install:
- composer install

script:
- ./vendor/bin/phpspec run

after_success:
- phpenv config-rm xdebug.ini
- composer scrutinizer
